services:
  - type: web
    name: segatech-site
    env: python
    region: oregon
    buildCommand: "cd sega && pip install -r requirements.txt"
    startCommand: "cd sega && gunicorn --bind 0.0.0.0:$PORT --workers 2 run:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_CODE
        value: "1234"
